swagger: "2.0"
info:
  description: "This is a Car Store server from AWS Course"
  version: "1.0.0"
  title: "Car Store"

host: "3xe5zb5ot5.execute-api.eu-west-1.amazonaws.com"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "product"
      summary: "Fetch all products"
      description: "Fetch all products from DB"
      operationId: "getProducts"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
  /products/{productId}:
    get:
      tags:
      - "product"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductsById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "Product not found"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      img:
        type: "string"
        format: "url"
      count:
        type: "integer"
        format: "int32"
      manufacturer:
        type: "string"
      model:
        type: "string"
      price:
        type: "integer"
        format: "int32"
    xml:
      name: "Product"
