service: authorization-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
