service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::car-app-import-bucket'
    - Effect: Allow
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::car-app-import-bucket/*'
    - Effect: Allow
      Action: 'sqs:*'
      Resource: 'arn:aws:sqs:eu-west-1:547071746265:catalogItemsQueue'
  environment:
    SQS_URL: 'https://sqs.eu-west-1.amazonaws.com/547071746265/catalogItemsQueue'

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  importProductFile:
    handler: handler.importProductFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:authorization-service-dev-basicAuthorizer
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: '^Basic [-0-9a-zA-Z._]*$'
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: car-app-import-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
